### ISSUE TITLE
Undefined variables in template file

### ISSUE THREAD

**Issue by joelstrom** [agencyleroy/rssfeeds#1]
Variables 'currentPage' and 'currentSiteHandle' seem to be undefined.

How to replicate: Click on the settings link from the Plugins view.

Craft: 3.3.3
rssfeeds: 1.0.2

**Comment by HyeinKang** [comment]
Cannot replicate this issue, would you mind putting more details?

**Comment by joelstrom** [comment]
Error still happens when clicking on the settings link (https://domain.test/admin/settings/plugins/rss-feeds) in the list of plugins, after updating to 1.0.4, and a fresh composer install.

![Screenshot 2020-08-20 at 14 32 20](https://user-images.githubusercontent.com/15905441/90765554-d4e59480-e2f2-11ea-94a3-c08fdad20723.png)

![Screenshot 2020-08-20 at 14 32 09](https://user-images.githubusercontent.com/15905441/90765378-7fa98300-e2f2-11ea-8107-c86e53ccfbd1.png)


Maybe it's related to some other issue?
